language: go
go_import_path: github.com/maticnetwork/heimdall
jobs:
  include:
    - stage: Docker Image Release
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io/amis
        - make docker
        - make docker.push
      if: tag =~ ^v([0-9]+.)+[0-9]+
      env: DOCKER_IMAGE_TAG="$TRAVIS_TAG"
